### Варіант № 3
### Завдання № 675
Дано дійсні числа $a_1, ..., a_n$, дійсна квадратна матриця порядку
$n (n \geq 6)$. Отримати дійсну матрицю розміру $n \times (n+1)$,
вставивши у початкову матрицю між п$`$ятим та шостим стовбцем новий
стовбець з елементами $a_1, ..., a_n$.

In [5]:
from random import randint
from numpy import matrix

try:
    n = int(input("Enter the order of the matrix:"))
    if n >= 6:
        a = [randint(-9, 9) for _ in range(n)]
        m = [[randint(-9, 9) for _ in range(n)] for _ in range(n)]
        print(f"Row a:\n{a}\nMatrix:\n{matrix(m)}")
        for i in range(n): m[i].insert(5, a[i])
        print(f"New matrix:\n{matrix(m)}")
    else:
        print("Input error!")
except ValueError:
    print("Input error!")

Row a:
[9, 9, -1, -1, -2, -7, 2, -8, -9, -8]
Matrix:
[[-8 -8  1  5 -6  3 -9  3  6 -2]
 [ 0 -2 -4 -4  2  8 -8  9 -6  4]
 [-3  2 -5 -7  0  4 -6  6  5  2]
 [-1 -3  3  4 -3 -9 -5 -8 -1 -3]
 [ 3 -1 -3 -3  0  6 -9  4  6 -7]
 [ 6  0 -6  2  8 -7 -4  2  2 -4]
 [ 3  7 -5  9 -8  1  0 -4 -7 -2]
 [ 6  0 -5  2  4 -5  2 -5 -7  1]
 [ 5 -2  9  7 -1 -1  8 -3  1  6]
 [-8  6  8 -5 -8 -9  0  4  1 -8]]
New matrix:
[[-8 -8  1  5 -6  9  3 -9  3  6 -2]
 [ 0 -2 -4 -4  2  9  8 -8  9 -6  4]
 [-3  2 -5 -7  0 -1  4 -6  6  5  2]
 [-1 -3  3  4 -3 -1 -9 -5 -8 -1 -3]
 [ 3 -1 -3 -3  0 -2  6 -9  4  6 -7]
 [ 6  0 -6  2  8 -7 -7 -4  2  2 -4]
 [ 3  7 -5  9 -8  2  1  0 -4 -7 -2]
 [ 6  0 -5  2  4 -8 -5  2 -5 -7  1]
 [ 5 -2  9  7 -1 -9 -1  8 -3  1  6]
 [-8  6  8 -5 -8 -8 -9  0  4  1 -8]]


# Examples

### Example 1
Row a:
[2, 9, -1, 7, -8, -7, -3]
Matrix:
[[-7 -1  5 -5 -7 -7  5]
 [ 5  2 -6  4 -8  9  8]
 [ 5 -5  6 -3  8 -4 -8]
 [-7 -7  8  0 -2  6 -8]
 [ 9  5 -4  4 -3 -9  0]
 [ 0 -2 -9 -6  6  9 -2]
 [-1  4 -4 -5  7  0  5]]
New matrix:
[[-7 -1  5 -5 -7  2 -7  5]
 [ 5  2 -6  4 -8  9  9  8]
 [ 5 -5  6 -3  8 -1 -4 -8]
 [-7 -7  8  0 -2  7  6 -8]
 [ 9  5 -4  4 -3 -8 -9  0]
 [ 0 -2 -9 -6  6 -7  9 -2]
 [-1  4 -4 -5  7 -3  0  5]]

### Example 2
Row a:
[4, -3, 8, 1, 9, 3]
Matrix:
[[-2  6  6 -8  6 -5]
 [ 7 -2 -3  7 -7 -1]
 [ 2  2  0 -3  4 -4]
 [ 8 -1  7 -9 -3 -7]
 [ 4  3 -3  1 -1 -2]
 [-7  9  8 -2  5 -2]]
New matrix:
[[-2  6  6 -8  6  4 -5]
 [ 7 -2 -3  7 -7 -3 -1]
 [ 2  2  0 -3  4  8 -4]
 [ 8 -1  7 -9 -3  1 -7]
 [ 4  3 -3  1 -1  9 -2]
 [-7  9  8 -2  5  3 -2]]

### Example 3
Row a:
[-7, -7, 5, 0, -8, 9, 5, -6, 4, -6]
Matrix:
[[-7  8 -2  3  9  5 -6 -2 -1  2]
 [-3 -2 -3 -3 -6  5 -2  6  0 -1]
 [ 2  6 -5  6 -9 -1 -9 -5 -7  1]
 [ 4 -7  1  4  7  3 -6 -8 -7  2]
 [-5  7 -4 -3  5  2 -4  0 -7 -8]
 [ 4 -7 -3  8  9  4  3  4 -7 -8]
 [-9 -8  4  3 -2  4 -5  1  8 -2]
 [-1 -9 -2  4  7  9  5  3  0  2]
 [-5  3  4 -8  6  2  5 -3  6 -7]
 [ 0 -9  7 -7  1  2  8 -6 -3  2]]
New matrix:
[[-7  8 -2  3  9 -7  5 -6 -2 -1  2]
 [-3 -2 -3 -3 -6 -7  5 -2  6  0 -1]
 [ 2  6 -5  6 -9  5 -1 -9 -5 -7  1]
 [ 4 -7  1  4  7  0  3 -6 -8 -7  2]
 [-5  7 -4 -3  5 -8  2 -4  0 -7 -8]
 [ 4 -7 -3  8  9  9  4  3  4 -7 -8]
 [-9 -8  4  3 -2  5  4 -5  1  8 -2]
 [-1 -9 -2  4  7 -6  9  5  3  0  2]
 [-5  3  4 -8  6  4  2  5 -3  6 -7]
 [ 0 -9  7 -7  1 -6  2  8 -6 -3  2]]